### ISSUE TITLE
Pattern filters do not seem to work

### ISSUE THREAD

**Issue by precondition** [Kuuuube/minimal-pairs#1]
![image](https://github.com/user-attachments/assets/c0e37c68-fc21-441b-966d-2e09102795d3)
As illustrated in the screenshot, ticking off all the nakadaka patterns gives me nonetheless a nakadaka word during the test.

I ticked off all those checkboxes when the tutorial was still visible.

After correctly answering this question, The nakadaka counter goes from `Nakadaka: 4 of 4 (100%)` to `Nakadaka: 5 of 5 (100%)`.

**Comment by Kuuuube** [comment]
Enable strict pair finding. The default is to find a pair with at least one of what you selected. Strict pair finding will only find pairs with exactly what you selected.

**Comment by precondition** [comment]
Ok thanks
